### ISSUE TITLE
PickRandomMethod returns exception

### ISSUE THREAD

**Issue by wubero** [ciselab/Lampion#109]
**Describe the bug**
When running a transformer on a dataset with the perClass transformation scope the program tries to apply the transformers to every class. This includes enums. However, when running the pickRandomMethod function the list of all methods is empty. This means that the bound for picking a random method is 0 which is not allowed.

**Expected behavior**
I expect this to be handled by either logging what is wrong or just ignoring the enums for this scope.

**Comment by lapplislazuli** [comment]
Closed with #120
