### ISSUE TITLE
Transformations in abstract classes with abstract methods give an error.

### ISSUE THREAD

**Issue by wubero** [ciselab/Lampion#91]
**Describe the bug**
The abstract methods in the abstract classes don't have a body, meaning that a part of the spoon library code returns null. This has not been handled meaning that it throws an exception.

**To Reproduce**
1. Run transformations on a class with only abstract methods

**Expected behavior**
What should happen, I think, is that the code ignores abstract methods.

**Comment by lapplislazuli** [comment]
Cross-Reference: 
I forwarded a bug-report to Spoon Maintainers 
https://github.com/INRIA/spoon/issues/4752 

It might be intended behaviour or could be Java-Spec.

**Comment by lapplislazuli** [comment]
Closed with #120
